name: Terraform Safe Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy with Dependency Order
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      # Step 1: Destroy EC2 instances or NAT gateways
      - name: Destroy Dependent Resources
        run: |
          terraform destroy -target=aws_instance.my_instance -target=aws_nat_gateway.my_nat -target=aws_eip.my_eip -auto-approve || true

      # Step 2: Destroy subnets and route associations
      - name: Destroy Subnets and IGW
        run: |
          terraform destroy -target=aws_route_table_association.public_rta \
                            -target=aws_subnet.subnet1 \
                            -target=aws_subnet.subnet2 \
                            -target=aws_internet_gateway.igw \
                            -auto-approve || true

      # Step 3: Destroy the rest
      - name: Destroy All Remaining Resources
        run: terraform destroy -auto-approve
