name: Terraform Safe Destroy

on:
  workflow_dispatch:  # Manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy with Dependency Cleanup
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: |
          terraform init
          terraform workspace select default || terraform workspace new default

      # 🧹 Cleanup ENIs, EIPs, NATs before Terraform destroy
      - name: AWS Pre-Destroy Cleanup
        run: |
          echo "🔍 Disassociating Elastic IPs..."
          for assoc_id in $(aws ec2 describe-addresses --region ap-south-1 --query "Addresses[?AssociationId!=null].AssociationId" --output text); do
            echo "➤ Disassociating $assoc_id"
            aws ec2 disassociate-address --association-id "$assoc_id" --region ap-south-1 || true
          done

          echo "🧹 Releasing Elastic IPs..."
          for alloc_id in $(aws ec2 describe-addresses --region ap-south-1 --query "Addresses[?AssociationId==null].AllocationId" --output text); do
            echo "➤ Releasing $alloc_id"
            aws ec2 release-address --allocation-id "$alloc_id" --region ap-south-1 || true
          done

          echo "🧹 Deleting unattached ENIs..."
          for eni_id in $(aws ec2 describe-network-interfaces --region ap-south-1 --query "NetworkInterfaces[?Status=='available'].NetworkInterfaceId" --output text); do
            echo "➤ Deleting ENI $eni_id"
            aws ec2 delete-network-interface --network-interface-id "$eni_id" --region ap-south-1 || true
          done

          echo "🧨 Deleting NAT Gateways..."
          for nat_id in $(aws ec2 describe-nat-gateways --region ap-south-1 --query "NatGateways[?State!='deleted'].NatGatewayId" --output text); do
            echo "➤ Deleting NAT Gateway $nat_id"
            aws ec2 delete-nat-gateway --nat-gateway-id "$nat_id" --region ap-south-1 || true
          done

      # 🧨 Single-step Terraform Destroy (no targets, fully automated)
      - name: Terraform Destroy All
        run: terraform destroy -auto-approve || true
